export const ques = [
  {
    question: 'What is the capital of France?',
    options: ['Berlin', 'Madrid', 'Paris', 'Rome'],
    correctAnswer: 'Paris',
    userAnswer: null,
    difficulty: 'easy',
  },
  {
    question: 'Which planet is known as the Red Planet?',
    options: ['Mars', 'Venus', 'Jupiter', 'Saturn'],
    correctAnswer: 'Mars',
    userAnswer: null,
    difficulty: 'medium',
  },
  {
    question: 'What is the capital of Germany?',
    options: ['Berlin', 'Munich', 'Frankfurt', 'Hamburg'],
    correctAnswer: 'Berlin',
    userAnswer: null,
    difficulty: 'easy',
  },
  {
    question: 'Which planet is closest to the sun?',
    options: ['Earth', 'Mars', 'Mercury', 'Venus'],
    correctAnswer: 'Mercury',
    userAnswer: null,
    difficulty: 'hard',
  },
  {
    question: 'What is the capital of Spain?',
    options: ['Barcelona', 'Madrid', 'Valencia', 'Seville'],
    correctAnswer: 'Madrid',
    userAnswer: null,
    difficulty: 'easy',
  },
  {
    question: 'Which planet is known as the Blue Planet?',
    options: ['Earth', 'Mars', 'Jupiter', 'Saturn'],
    correctAnswer: 'Earth',
    userAnswer: null,
    difficulty: 'medium',
  },
  {
    question: 'What is the capital of Italy?',
    options: ['Rome', 'Milan', 'Naples', 'Turin'],
    correctAnswer: 'Rome',
    userAnswer: null,
    difficulty: 'easy',
  },
  {
    question: 'Which planet is known as the Gas Giant?',
    options: ['Mars', 'Jupiter', 'Saturn', 'Uranus'],
    correctAnswer: 'Jupiter',
    userAnswer: null,
    difficulty: 'hard',
  },
  {
    question: 'What is the capital of the United Kingdom?',
    options: ['London', 'Manchester', 'Birmingham', 'Leeds'],
    correctAnswer: 'London',
    userAnswer: null,
    difficulty: 'easy',
  },
  {
    question: 'Which planet is known as the Ringed Planet?',
    options: ['Mars', 'Jupiter', 'Saturn', 'Uranus'],
    correctAnswer: 'Saturn',
    userAnswer: null,
    difficulty: 'medium',
  },
];